simcir.registerDevice('4BitRam',
    {
        "width": 600,
        "height": 400,
        "showToolbox": false,
        "devices": [
            {"id": "dev0", "label": "D-FF", "type": "D-FF", "x": 352, "y": 184},
            {"id": "dev1", "label": "D-FF", "type": "D-FF", "x": 352, "y": 72},
            {"id": "dev2", "label": "D-FF", "type": "D-FF", "x": 352, "y": 128},
            {"type": "Out", "id": "dev3", "x": 440, "y": 24, "label": "O0"},
            {"type": "Out", "id": "dev4", "x": 440, "y": 72, "label": "O1"},
            {"type": "Out", "id": "dev5", "x": 440, "y": 120, "label": "O2"},
            {"type": "Out", "id": "dev6", "x": 440, "y": 168, "label": "O3"},
            {"id": "dev7", "label": "Toggle", "state": {"on": false}, "type": "Toggle", "x": 152, "y": 24},
            {"id": "dev8", "label": "Toggle", "state": {"on": true}, "type": "Toggle", "x": 152, "y": 80},
            {"id": "dev9", "label": "Toggle", "state": {"on": false}, "type": "Toggle", "x": 152, "y": 128},
            {"type": "Toggle", "id": "dev10", "x": 152, "y": 184, "label": "Toggle", "state": {"on": false}},
            {"type": "PushOn", "id": "dev11", "x": 88, "y": 112, "label": "PushOn"},
            {"type": "In", "id": "dev12", "x": 224, "y": 24, "label": "0"},
            {"type": "In", "id": "dev13", "x": 224, "y": 72, "label": "1"},
            {"type": "In", "id": "dev14", "x": 224, "y": 128, "label": "2"},
            {"type": "In", "id": "dev15", "x": 224, "y": 184, "label": "3"},
            {"type": "In", "id": "dev16", "x": 224, "y": 232, "label": "On"},
            {"id": "dev17", "label": "DC", "type": "DC", "x": 24, "y": 112},
            {"type": "NOT", "id": "dev18", "x": 288, "y": 24, "label": "NOT"},
            {"type": "NOT", "id": "dev19", "x": 288, "y": 72, "label": "NOT"},
            {"id": "dev20", "label": "D-FF", "type": "D-FF", "x": 352, "y": 24},
            {"type": "NOT", "id": "dev21", "x": 288, "y": 128, "label": "NOT"},
            {"type": "NOT", "id": "dev22", "x": 288, "y": 184, "label": "NOT"}
        ],
        "connectors": [
            {"from": "dev0.in0", "to": "dev22.out0"},
            {"from": "dev0.in1", "to": "dev16.out0"},
            {"from": "dev1.in0", "to": "dev19.out0"},
            {"from": "dev1.in1", "to": "dev16.out0"},
            {"from": "dev2.in0", "to": "dev21.out0"},
            {"from": "dev2.in1", "to": "dev16.out0"},
            {"from": "dev3.in0", "to": "dev20.out1"},
            {"from": "dev4.in0", "to": "dev1.out1"},
            {"from": "dev5.in0", "to": "dev2.out1"},
            {"from": "dev6.in0", "to": "dev0.out1"},
            {"from": "dev7.in0", "to": "dev11.out0"},
            {"from": "dev8.in0", "to": "dev11.out0"},
            {"from": "dev9.in0", "to": "dev11.out0"},
            {"from": "dev10.in0", "to": "dev11.out0"},
            {"from": "dev11.in0", "to": "dev17.out0"},
            {"from": "dev12.in0", "to": "dev7.out0"},
            {"from": "dev13.in0", "to": "dev8.out0"},
            {"from": "dev14.in0", "to": "dev9.out0"},
            {"from": "dev15.in0", "to": "dev10.out0"},
            {"from": "dev16.in0", "to": "dev11.out0"},
            {"from": "dev18.in0", "to": "dev12.out0"},
            {"from": "dev19.in0", "to": "dev13.out0"},
            {"from": "dev20.in0", "to": "dev18.out0"},
            {"from": "dev20.in1", "to": "dev16.out0"},
            {"from": "dev21.in0", "to": "dev14.out0"},
            {"from": "dev22.in0", "to": "dev15.out0"}
        ]
    }
);
simcir.registerDevice('If1',
    {
        "width": 600,
        "height": 400,
        "showToolbox": false,
        "devices": [
            {"type": "Toggle", "id": "dev0", "x": 112, "y": 40, "label": "Toggle", "state": {"on": false}},
            {"type": "Toggle", "id": "dev1", "x": 112, "y": 96, "label": "Toggle", "state": {"on": false}},
            {"type": "Toggle", "id": "dev2", "x": 112, "y": 144, "label": "Toggle", "state": {"on": false}},
            {"type": "DC", "id": "dev3", "x": 48, "y": 128, "label": "DC"},
            {"type": "In", "id": "dev4", "x": 184, "y": 88, "label": "1"},
            {"type": "In", "id": "dev5", "x": 184, "y": 40, "label": "0"},
            {"type": "In", "id": "dev6", "x": 184, "y": 200, "label": "3"},
            {"type": "In", "id": "dev7", "x": 184, "y": 144, "label": "2"},
            {"type": "Toggle", "id": "dev8", "x": 112, "y": 200, "label": "Toggle", "state": {"on": false}},
            {"type": "AND", "id": "dev9", "x": 376, "y": 48, "label": "AND"},
            {"type": "NOR", "id": "dev10", "x": 304, "y": 96, "label": "NOR"},
            {"type": "OR", "id": "dev11", "x": 264, "y": 168, "label": "OR"},
            {"type": "Out", "id": "dev12", "x": 472, "y": 48, "label": "Out"}
        ],
        "connectors": [
            {"from": "dev0.in0", "to": "dev3.out0"},
            {"from": "dev1.in0", "to": "dev3.out0"},
            {"from": "dev2.in0", "to": "dev3.out0"},
            {"from": "dev4.in0", "to": "dev1.out0"},
            {"from": "dev5.in0", "to": "dev0.out0"},
            {"from": "dev6.in0", "to": "dev8.out0"},
            {"from": "dev7.in0", "to": "dev2.out0"},
            {"from": "dev8.in0", "to": "dev3.out0"},
            {"from": "dev9.in0", "to": "dev5.out0"},
            {"from": "dev9.in1", "to": "dev10.out0"},
            {"from": "dev10.in0", "to": "dev4.out0"},
            {"from": "dev10.in1", "to": "dev11.out0"},
            {"from": "dev11.in0", "to": "dev7.out0"},
            {"from": "dev11.in1", "to": "dev6.out0"},
            {"from": "dev12.in0", "to": "dev9.out0"}
        ]
    }
);
simcir.registerDevice('N_If_On_Else_D',
    {
        "width": 600,
        "height": 400,
        "showToolbox": false,
        "devices": [
            {"type": "Toggle", "id": "dev0", "x": 120, "y": 104, "label": "Toggle", "state": {"on": false}},
            {"type": "Toggle", "id": "dev1", "x": 120, "y": 48, "label": "Toggle", "state": {"on": false}},
            {"type": "In", "id": "dev2", "x": 176, "y": 104, "label": "N"},
            {"type": "In", "id": "dev3", "x": 176, "y": 48, "label": "D"},
            {"type": "Toggle", "id": "dev4", "x": 120, "y": 160, "label": "Toggle", "state": {"on": false}},
            {"type": "DC", "id": "dev5", "x": 48, "y": 104, "label": "DC"},
            {"type": "AND", "id": "dev6", "x": 304, "y": 56, "label": "AND"},
            {"type": "OR", "id": "dev7", "x": 392, "y": 80, "label": "OR"},
            {"type": "Out", "id": "dev8", "x": 448, "y": 80, "label": "Out"},
            {"type": "In", "id": "dev9", "x": 176, "y": 160, "label": "On"},
            {"type": "NOT", "id": "dev10", "x": 248, "y": 112, "label": "NOT"},
            {"type": "AND", "id": "dev11", "x": 328, "y": 112, "label": "AND"}
        ],
        "connectors": [
            {"from": "dev0.in0", "to": "dev5.out0"},
            {"from": "dev1.in0", "to": "dev5.out0"},
            {"from": "dev2.in0", "to": "dev0.out0"},
            {"from": "dev3.in0", "to": "dev1.out0"},
            {"from": "dev4.in0", "to": "dev5.out0"},
            {"from": "dev6.in0", "to": "dev3.out0"},
            {"from": "dev6.in1", "to": "dev10.out0"},
            {"from": "dev7.in0", "to": "dev6.out0"},
            {"from": "dev7.in1", "to": "dev11.out0"},
            {"from": "dev8.in0", "to": "dev7.out0"},
            {"from": "dev9.in0", "to": "dev4.out0"},
            {"from": "dev10.in0", "to": "dev9.out0"},
            {"from": "dev11.in0", "to": "dev2.out0"},
            {"from": "dev11.in1", "to": "dev9.out0"}
        ]
    }
);
simcir.registerDevice('4BitNOD',
    {
        "width": 500,
        "height": 600,
        "showToolbox": false,
        "devices": [
            {"type": "In", "id": "dev0", "x": 48, "y": 32, "label": "N0"},
            {"type": "In", "id": "dev1", "x": 48, "y": 80, "label": "N1"},
            {"type": "In", "id": "dev2", "x": 48, "y": 128, "label": "N2"},
            {"type": "In", "id": "dev3", "x": 48, "y": 176, "label": "N3"},
            {"type": "In", "id": "dev4", "x": 48, "y": 224, "label": "D0"},
            {"type": "In", "id": "dev5", "x": 48, "y": 272, "label": "D1"},
            {"type": "In", "id": "dev6", "x": 48, "y": 376, "label": "D3"},
            {"type": "N_If_On_Else_D", "id": "dev7", "x": 192, "y": 136, "label": "N_If_On_Else_D"},
            {"type": "In", "id": "dev8", "x": 48, "y": 424, "label": "On"},
            {"type": "Out", "id": "dev9", "x": 328, "y": 144, "label": "O0"},
            {"type": "Out", "id": "dev10", "x": 328, "y": 208, "label": "O1"},
            {"type": "N_If_On_Else_D", "id": "dev11", "x": 192, "y": 208, "label": "N_If_On_Else_D"},
            {"type": "N_If_On_Else_D", "id": "dev12", "x": 192, "y": 288, "label": "N_If_On_Else_D"},
            {"type": "In", "id": "dev13", "x": 48, "y": 320, "label": "D2"},
            {"type": "Out", "id": "dev14", "x": 328, "y": 280, "label": "O2"},
            {"type": "Out", "id": "dev15", "x": 328, "y": 368, "label": "O3"},
            {"type": "N_If_On_Else_D", "id": "dev16", "x": 192, "y": 368, "label": "N_If_On_Else_D"}
        ],
        "connectors": [
            {"from": "dev7.in0", "to": "dev4.out0"},
            {"from": "dev7.in1", "to": "dev0.out0"},
            {"from": "dev7.in2", "to": "dev8.out0"},
            {"from": "dev9.in0", "to": "dev7.out0"},
            {"from": "dev10.in0", "to": "dev11.out0"},
            {"from": "dev11.in0", "to": "dev5.out0"},
            {"from": "dev11.in1", "to": "dev1.out0"},
            {"from": "dev11.in2", "to": "dev8.out0"},
            {"from": "dev12.in0", "to": "dev13.out0"},
            {"from": "dev12.in1", "to": "dev2.out0"},
            {"from": "dev12.in2", "to": "dev8.out0"},
            {"from": "dev14.in0", "to": "dev12.out0"},
            {"from": "dev15.in0", "to": "dev16.out0"},
            {"from": "dev16.in0", "to": "dev6.out0"},
            {"from": "dev16.in1", "to": "dev3.out0"},
            {"from": "dev16.in2", "to": "dev8.out0"}
        ]
    }
);
simcir.registerDevice('4BitMulti',
    {
  "width":1200,
  "height":800,
  "showToolbox":false,
  "devices":[
    {"type":"In","id":"dev0","x":144,"y":72,"label":"A0"},
    {"type":"In","id":"dev1","x":144,"y":128,"label":"A1"},
    {"type":"In","id":"dev2","x":144,"y":184,"label":"A2"},
    {"type":"In","id":"dev3","x":144,"y":240,"label":"A3"},
    {"type":"In","id":"dev4","x":144,"y":288,"label":"B0"},
    {"type":"In","id":"dev5","x":144,"y":344,"label":"B1"},
    {"type":"In","id":"dev6","x":144,"y":400,"label":"B2"},
    {"type":"In","id":"dev7","x":144,"y":456,"label":"B3"},
    {"type":"AND","id":"dev8","x":328,"y":88,"label":"AND"},
    {"type":"AND","id":"dev9","x":328,"y":136,"label":"AND"},
    {"type":"AND","id":"dev10","x":328,"y":184,"label":"AND"},
    {"type":"AND","id":"dev11","x":328,"y":232,"label":"AND"},
    {"type":"AND","id":"dev12","x":328,"y":304,"label":"AND"},
    {"type":"AND","id":"dev13","x":328,"y":360,"label":"AND"},
    {"type":"AND","id":"dev14","x":328,"y":408,"label":"AND"},
    {"type":"AND","id":"dev15","x":328,"y":456,"label":"AND"},
    {"type":"AND","id":"dev16","x":456,"y":424,"label":"AND"},
    {"type":"AND","id":"dev17","x":456,"y":368,"label":"AND"},
    {"type":"AND","id":"dev18","x":456,"y":480,"label":"AND"},
    {"type":"Out","id":"dev19","x":608,"y":88,"label":"O0"},
    {"type":"4bitAdder","id":"dev20","x":608,"y":152,"label":"4bitAdder"},
    {"type":"4bitAdder","id":"dev21","x":432,"y":40,"label":"4bitAdder"},
    {"type":"FullAdder","id":"dev22","x":432,"y":192,"label":"FullAdder"},
    {"type":"FullAdder","id":"dev23","x":608,"y":304,"label":"FullAdder"},
    {"type":"Out","id":"dev24","x":744,"y":120,"label":"O1"},
    {"type":"AND","id":"dev25","x":632,"y":408,"label":"AND"},
    {"type":"AND","id":"dev26","x":640,"y":456,"label":"AND"},
    {"type":"AND","id":"dev27","x":640,"y":504,"label":"AND"},
    {"type":"AND","id":"dev28","x":632,"y":552,"label":"AND"},
    {"type":"FullAdder","id":"dev29","x":768,"y":432,"label":"FullAdder"},
    {"type":"Out","id":"dev30","x":920,"y":288,"label":"O2"},
    {"type":"Out","id":"dev31","x":920,"y":344,"label":"O3"},
    {"type":"Out","id":"dev32","x":920,"y":456,"label":"C1"},
    {"type":"Out","id":"dev33","x":928,"y":504,"label":"C2"},
    {"type":"Out","id":"dev34","x":928,"y":552,"label":"C3"},
    {"type":"Out","id":"dev35","x":920,"y":400,"label":"C0"},
    {"type":"4bitAdder","id":"dev36","x":768,"y":272,"label":"4bitAdder"},
    {"type":"AND","id":"dev37","x":456,"y":312,"label":"AND"}
  ],
  "connectors":[
    {"from":"dev8.in0","to":"dev0.out0"},
    {"from":"dev8.in1","to":"dev4.out0"},
    {"from":"dev9.in0","to":"dev0.out0"},
    {"from":"dev9.in1","to":"dev5.out0"},
    {"from":"dev10.in0","to":"dev0.out0"},
    {"from":"dev10.in1","to":"dev6.out0"},
    {"from":"dev11.in0","to":"dev0.out0"},
    {"from":"dev11.in1","to":"dev7.out0"},
    {"from":"dev12.in0","to":"dev1.out0"},
    {"from":"dev12.in1","to":"dev4.out0"},
    {"from":"dev13.in0","to":"dev1.out0"},
    {"from":"dev13.in1","to":"dev5.out0"},
    {"from":"dev14.in0","to":"dev1.out0"},
    {"from":"dev14.in1","to":"dev6.out0"},
    {"from":"dev15.in0","to":"dev1.out0"},
    {"from":"dev15.in1","to":"dev7.out0"},
    {"from":"dev16.in0","to":"dev2.out0"},
    {"from":"dev16.in1","to":"dev6.out0"},
    {"from":"dev17.in0","to":"dev2.out0"},
    {"from":"dev17.in1","to":"dev5.out0"},
    {"from":"dev18.in0","to":"dev2.out0"},
    {"from":"dev18.in1","to":"dev7.out0"},
    {"from":"dev19.in0","to":"dev21.out0"},
    {"from":"dev20.in1","to":"dev21.out1"},
    {"from":"dev20.in2","to":"dev21.out2"},
    {"from":"dev20.in3","to":"dev21.out3"},
    {"from":"dev20.in4","to":"dev22.out0"},
    {"from":"dev20.in6","to":"dev37.out0"},
    {"from":"dev20.in7","to":"dev17.out0"},
    {"from":"dev20.in8","to":"dev16.out0"},
    {"from":"dev21.in1","to":"dev8.out0"},
    {"from":"dev21.in2","to":"dev9.out0"},
    {"from":"dev21.in3","to":"dev10.out0"},
    {"from":"dev21.in4","to":"dev11.out0"},
    {"from":"dev21.in6","to":"dev12.out0"},
    {"from":"dev21.in7","to":"dev13.out0"},
    {"from":"dev21.in8","to":"dev14.out0"},
    {"from":"dev22.in0","to":"dev21.out4"},
    {"from":"dev22.in2","to":"dev15.out0"},
    {"from":"dev23.in0","to":"dev20.out4"},
    {"from":"dev23.in1","to":"dev22.out1"},
    {"from":"dev23.in2","to":"dev18.out0"},
    {"from":"dev24.in0","to":"dev20.out0"},
    {"from":"dev25.in0","to":"dev3.out0"},
    {"from":"dev25.in1","to":"dev4.out0"},
    {"from":"dev26.in0","to":"dev3.out0"},
    {"from":"dev26.in1","to":"dev5.out0"},
    {"from":"dev27.in0","to":"dev3.out0"},
    {"from":"dev27.in1","to":"dev6.out0"},
    {"from":"dev28.in0","to":"dev3.out0"},
    {"from":"dev28.in1","to":"dev7.out0"},
    {"from":"dev29.in0","to":"dev36.out4"},
    {"from":"dev29.in1","to":"dev23.out1"},
    {"from":"dev29.in2","to":"dev28.out0"},
    {"from":"dev30.in0","to":"dev36.out0"},
    {"from":"dev31.in0","to":"dev36.out1"},
    {"from":"dev32.in0","to":"dev36.out3"},
    {"from":"dev33.in0","to":"dev29.out0"},
    {"from":"dev34.in0","to":"dev29.out1"},
    {"from":"dev35.in0","to":"dev36.out2"},
    {"from":"dev36.in1","to":"dev20.out1"},
    {"from":"dev36.in2","to":"dev20.out2"},
    {"from":"dev36.in3","to":"dev20.out3"},
    {"from":"dev36.in4","to":"dev23.out0"},
    {"from":"dev36.in6","to":"dev25.out0"},
    {"from":"dev36.in7","to":"dev26.out0"},
    {"from":"dev36.in8","to":"dev27.out0"},
    {"from":"dev37.in0","to":"dev2.out0"},
    {"from":"dev37.in1","to":"dev4.out0"}
  ]
}
);
simcir.registerDevice('If10',
    {
  "width":800,
  "height":800,
  "showToolbox":false,
  "devices":[
    {"type":"In","id":"dev0","x":112,"y":96,"label":"0"},
    {"type":"In","id":"dev1","x":112,"y":192,"label":"2"},
    {"type":"In","id":"dev2","x":112,"y":240,"label":"3"},
    {"type":"OR","id":"dev3","x":208,"y":208,"label":"OR"},
    {"type":"NOR","id":"dev4","x":280,"y":144,"label":"NOR"},
    {"type":"In","id":"dev5","x":112,"y":144,"label":"1"},
    {"type":"AND","id":"dev6","x":344,"y":96,"label":"AND"},
    {"type":"Out","id":"dev7","x":424,"y":112,"label":"Out"}
  ],
  "connectors":[
    {"from":"dev3.in0","to":"dev1.out0"},
    {"from":"dev3.in1","to":"dev2.out0"},
    {"from":"dev4.in0","to":"dev0.out0"},
    {"from":"dev4.in1","to":"dev3.out0"},
    {"from":"dev6.in0","to":"dev5.out0"},
    {"from":"dev6.in1","to":"dev4.out0"},
    {"from":"dev7.in0","to":"dev6.out0"}
  ]
});